# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  name: 'COMP367-Windows'

variables: 
  buildConfiguration: 'Release'
  Major: '1'
  Minor: '0'
  Patch: '0'
  PackageVersion: '$(Major).$(Minor).$(Patch)'  # Version for the NuGet package
  dotNetVersion: '8.0.x'  # .NET 8 version
  projectPath: 'StringExtensions/StringExtensions.csproj'  # Path to your project file (update if needed)

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8 SDK'
  inputs:
    version: '8.0.x'
    packageType: 'sdk'
    installationPath: $(Agent.ToolsDirectory)/dotnet


- task: DotNetCoreCLI@2  # Restore packages
  displayName: 'Restore'
  inputs: 
    command: 'restore'
    projects: '$(projectPath)'

- task: DotNetCoreCLI@2  # Build the solution
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2  # Create NuGet package
  displayName: 'Pack'
  inputs:
    command: 'pack'
    packagesToPack: '$(projectPath)'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'PackageVersion'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    nobuild: true  # Skip build since it's already done

- task: NuGetAuthenticate@1  # Authenticate with Azure Artifacts
  displayName: 'Authenticate with Azure Artifacts'

- task: NuGetCommand@2  # Push package to feed
  displayName: 'Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'string-utilities-project/Lab4Feed2'  # Update to your actual feed
    allowPackageConflicts: true

- task: PublishBuildArtifacts@1  # Publish build artifacts
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

